#### Numpy
- Numpy stands for Numerical Python
- Basic and one of the most important library for numerical computations
- Supports N-dimensional array objects that can be used for processing multidimensional data
- Supports different data-types

##### Using Numpy we can perform

- Mathematical and logical operations on arrays
- Fourier transforms
- Linear algebra operations
- Random number generation

In [3]:
import numpy as np

### How to Create arrray
##### 1. using np.array method

- Ordered collection of elements of basic data types of given length
- Syntax: numpy.array(object)

In [4]:
array1=np.array([1,2,3,4,5,6])
print(array1)
type(array1)
print(array1.dtype)

[1 2 3 4 5 6]
int32


In [5]:
array2=np.array([1,2,3,4,6])
print(array2)
type(array2[0])

[1 2 3 4 6]


numpy.int32

In [6]:
type(array2)

numpy.ndarray

In [7]:
print(array2.dtype)

int32


##### Important Note - 
- Arrray in python is collection of different datatype elements
- All elements are coerced(converted) to same data type i.e conversion will be done of lower datatype elements to higher datatype elements

In [10]:
arr1=np.array([2,3,5.6,'n'])
print(arr1)
print(type(arr1))
print(type(arr1[0]))
print(type(arr1[1]))
print(type(arr1[2]))
print(type(arr1[3]))

['2' '3' '5.6' 'n']
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### 2. Generate arrays using arange( )
- numpy.arange()- returns equally spaced numbers with in the given range based on step size
- Syntax:numpy.arange(start,stop,step)
- start - start of interval range
- stop - end of interval range
- step - step size of interval

In [13]:
a1=np.arange(10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a3=np.arange(start=110,stop=120,step=3)
print(a3)

[110 113 116 119]


- Create array of elements between 70 to 50 with 5 difference

In [16]:
a4=np.arange(start=70,stop=50,step=-5)
print(a4)

[70 65 60 55]


#### 3. Generate arrays using ones
- numpy.ones()- returns an array of given shape and type filled with ones
- Syntax:numpy.ones(shape,dtype)
- shape - integer or sequence of integers
- dtype - data type (default:float)

In [17]:
arr4= np.ones(6)
print(arr4)

[1. 1. 1. 1. 1. 1.]


In [19]:
arr5= np.ones((3,7),int)
print(arr5)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


##### 4. Generate arrays using zeros
- numpy.zeros()- returns an array of given shape and type filled with zeros
- Syntax:numpy.zeros(shape,dtype)
- shape - integer or sequence of integers
- dtype - data type (default:float)

In [20]:
arr7= np.zeros(6)
print(arr7)

[0. 0. 0. 0. 0. 0.]


In [21]:
arr8= np.zeros((3,7),int)
print(arr8)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


#### 5. Generate arrays using random.rand( )
- numpy.random.rand()- returns an array of given shape filled with random values
- Syntax:numpy.random.rand(shape)
- shape - integer or sequence of integers

In [22]:
# Create 1D array of 5 random elements between 0 to 1
a10=np.random.rand(5)
print(a10)

[0.70769051 0.07959679 0.0270112  0.71593833 0.37244351]


In [23]:
# Create 2D array of 35 random elements between 0 to 1
a11=np.random.rand(7,5)
print(a11)

[[0.15214003 0.19708297 0.16276431 0.54359435 0.24557292]
 [0.61264025 0.01037342 0.90538903 0.76597091 0.31186085]
 [0.17024339 0.05469921 0.55749989 0.5305304  0.36007295]
 [0.06751719 0.94718553 0.81189866 0.72678939 0.8625538 ]
 [0.35917299 0.2026654  0.09913137 0.27899681 0.15080301]
 [0.40106968 0.42107051 0.14349022 0.19431558 0.53751132]
 [0.57772903 0.35364089 0.10264882 0.03296459 0.45056645]]


In [24]:
# Create 2D array of 35 random int elements between 100 to 150
a12=np.random.randint(100,150,(7,5))
print(a12)

[[144 146 110 132 131]
 [121 102 126 107 109]
 [132 100 144 126 110]
 [134 126 107 132 144]
 [106 144 125 106 115]
 [122 100 142 118 140]
 [108 133 103 107 127]]


1. Speed - Array is faster than list
2. Memory Storage - Array takes less memory than list

In [31]:
import time

In [32]:
# Consider case for List
py_list=[i for i in range(100000)]
start=time.time()
py_list=[i+2 for i in py_list]
stop=time.time()
print(stop-start)

0.011000394821166992


In [33]:
# Consider case for Numpy Array
py_arr=np.array([i for i in range(1000000)])
start=time.time()
py_arr=py_arr+2
stop=time.time()
print(stop-start)

0.002000093460083008


##### Storage Space - 

In [34]:
import sys

In [35]:
a1=np.arange(100)
print(type(a1))
print(a1.size)
print("Total space taken by a1 is",a1.itemsize*100)

<class 'numpy.ndarray'>
100
Total space taken by a1 is 400


In [36]:
l1=[i for i in range(100)]

In [37]:
len(l1)

100

In [38]:
print("Total size taken by l1 =",sys.getsizeof(l1[0])*len(l1))

Total size taken by l1 = 2400


- Operations

Reshape - We can change shape of arrays

In [39]:
a=np.array([[1,2,3,4],[6,7,8,9]])
print(a)
print(a.shape)

[[1 2 3 4]
 [6 7 8 9]]
(2, 4)


In [40]:
b=a.reshape(4,2)
print(b)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [41]:
b.shape

(4, 2)

##### Arrithmetic Operations in Numpy

In [55]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[11,12,13],[14,15,16],[17,18,19]])
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [56]:
print("addditon of a1 and a2 is\n",np.add(a1,a2))

addditon of a1 and a2 is
 [[12 14 16]
 [18 20 22]
 [24 26 28]]


In [57]:
print("subtract of a1 and a2 is\n",np.subtract(a1,a2))

subtract of a1 and a2 is
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [58]:
print("mul of a1 and a2 is\n",np.multiply(a1,a2))

mul of a1 and a2 is
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [59]:
print("divide of a1 and a2 is\n",np.divide(a2,a1))

divide of a1 and a2 is
 [[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [60]:
print("remainder of a1 and a2 is\n",np.remainder(a2,a1))

remainder of a1 and a2 is
 [[0 0 1]
 [2 0 4]
 [3 2 1]]


#### Statistical Functions

In [3]:
import numpy as np
arr = np.array([[1,4,2],[3,4,6],[0,-2,5]])
print(np.amin(arr),',',np.amax(arr))

-2 , 6


In [5]:
a = np.array([5,4,7,10,2,34,54,98,53])
print('Mean: ', round(np.mean(a),2))
print('Median: ',np.median(a))

Mean:  29.67
Median:  10.0


In [11]:
data = [32,36,46,47,56,69,75,79,88,89,91,92,93,96,97,101,105,112,116,122]
Q1 = np.median(data[:10])
Q3 = np.median(data[10:])
IQR = Q3-Q1
print(IQR)

36.5


In [12]:
Q1 =np.percentile(data, 25, interpolation = 'midpoint')
Q3 =np.percentile(data, 75, interpolation = 'midpoint')
IQR = Q3-Q1
print(IQR)

36.5
