In [1]:
!pip install opencv-python

In [2]:
import cv2
cv2.__version__
# Checking opencv version

'4.5.1'

In [3]:
import numpy as np
import matplotlib.pyplot as plt
img = np.array([[1,4,2,3]])
plt.imshow(img,cmap='gray') # Plotting the Image
#plt.axis('off') 
plt.show()

<Figure size 640x480 with 1 Axes>

## **Numpy Array Datatype:**


Image pixel values will be in the range of 0-255 

uint8 - Range (0 to 255)

0 indicates - Black

255 indicates -  White

In [ ]:
# Black Image
import numpy as np
img = np.zeros([100,100],dtype='uint8') # Taking numpy array with 100 * 100 pixels and zeros values

print(img)
print(img.ndim)
cv2.imshow('Output',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
2


In [ ]:
# Close Image window by pressing any key from keyboard (esc is preferred) before running next cell else * mark will be there

In [5]:
# White Image
img = np.ones([100,100],dtype='uint8')*255
cv2.imshow('Output',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
# Gray Image
img = np.ones([100,100],dtype='uint8')*127 # Array Broadcasting with a a value of 127 for all the pixels
cv2.imshow('Output',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
# Taking random values
x = 127
img = np.ones([100,100],dtype='uint8')*x
cv2.imshow('Output_Gray',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# Colored Image
img = np.ones([100,100,3],dtype='uint8')*255
img[:,:] = [255,255,0] # BGR = Blue, Green, Red (Opencv follows BGR Method)
cv2.imshow('Output',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
img = np.ones([300,300,3],dtype='uint8')*255
img[0:100,:] = [255,0,0] # Changing the rows values to one specific color
img[101:200,:] = [0,255,0]
img[201:300,:] = [0,0,255]
cv2.imshow('Output',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Refer https://www.w3schools.com/colors/colors_rgb.asp for getting RGB values

In [13]:
!pip install wget
!python -m wget https://www.ciobulletin.com/assets/home_image/ciobulletin-microsoft-sap-partnership-announcement.jpg -o demo.jpg


Saved under demo.jpg


In [15]:
# How to read an Image
img = cv2.imread('demo.jpg')
cv2.imshow('Output',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(img.ndim) # Taking the Dimension of an Image
print(img.shape) # Height*Width*Depth of an Image

3
(499, 840, 3)


In [17]:
# Resizing it to 200*400 Pixels
img = cv2.imread('demo.jpg')
img = cv2.resize(img,(420,250)) 
cv2.imshow('Output',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
# Saving a New Image
cv2.imwrite('demo_new.jpg',img)

True

In [19]:
# How to get Grayscale Image from Colored Image?
# Method 1: Using COLOR_BGR2GRAY attribute
img = cv2.imread('demo_new.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('Gray',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
# Method 2: Using COLOR_BGR2GRAY attribute
img = cv2.imread('demo_new.jpg',0)
cv2.imshow('Output',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
# How to get Binary Image
img = cv2.imread('demo_new.jpg',0)
_,thresh = cv2.threshold(img,127,255,cv2.THRESH_BINARY)
#_,thresh = cv2.threshold(img,127,255,cv2.THRESH_BINARY_INV) # Try this
cv2.imshow('Binary',thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
#https://docs.opencv.org/master/d7/d4d/tutorial_py_thresholding.html

# **CONVOLUTION MATRIX**

In [22]:
# Applying Box BLur of Kernel 3*3
import numpy as np
img = cv2.imread('demo_new.jpg')
filter1 = np.array([[1,1,1],
                    [1,1,1],
                    [1,1,1]])*(1/9)
op = cv2.filter2D(img,-1,filter1)
cv2.imshow('Output',op)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Reference : https://en.wikipedia.org/wiki/Kernel_(image_processing)

In [23]:
# Applying Box BLur of Kernel 5*5
import numpy as np
img = cv2.imread('demo_new.jpg')
filter2 = np.array([[1,4,6,4,1],
                    [4,16,24,16,4],
                    [6,24,36,26,6],
                    [4,16,24,16,4],
                    [1,4,6,4,1]])*(1/256)
op = cv2.filter2D(img,-1,filter2)
cv2.imshow('Output',op)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
# Edge Detection Filter
import numpy as np
img = cv2.imread('demo_new.jpg',0)
filter3 = np.array([[-1,-1,-1],
                    [-1,8,-1],
                    [-1,-1,-1]])
op = cv2.filter2D(img,-1,filter3)
cv2.imshow('Output',op)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
# Direct Blur Function
img = cv2.imread('demo_new.jpg')
a1 = cv2.blur(img,(3,3))
a2 = cv2.blur(img,(5,5))
a3 = cv2.blur(img,(9,9))
a4 = cv2.blur(img,(11,11))
cv2.imshow('Original',img)
cv2.imshow('Blur 1 Image',a1)
cv2.imshow('Blur 2 Image',a2)
cv2.imshow('Blur 3 Image',a3)
cv2.imshow('Blur 4 Image',a4)
cv2.waitKey(0)
cv2.destroyAllWindows()

#(3,3),(5,5),(9,9) are the Kernel sizes
# The higher Kernel size value, the more blur output image will be

In [31]:
# Edge Detection using Canny
img = cv2.imread('demo_new.jpg')
edge = cv2.Canny(img,127,127)
cv2.imshow('Edge Detection Image',edge)
cv2.waitKey(0)
cv2.destroyAllWindows()
# Threshold value 1 and Threshold value 2
# https://docs.opencv.org/master/da/d22/tutorial_py_canny.html

In [ ]:
# Facial Detection


In [34]:
!python -m wget https://www.eatright.org/-/media/eatrightimages/health/weightloss/yourhealthandyourweight/promote-positive-body-image-kids-839295596.jpg -o people.jpg


Saved under people.jpg


In [35]:
import cv2
test_image = cv2.imread('people.jpg')
cv2.rectangle(test_image,(50,25),(200,100),(0,255,255),10) # To get rectangle shape in Opencv
cv2.imshow('Image',test_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [36]:
!python -m wget https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_frontalface_default.xml

# Downloading thee xml file of Cascade Classifier from Gituhb repository of opencv


Saved under haarcascade_frontalface_default.xml


In [39]:
!python -m wget https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_eye.xml


Saved under haarcascade_eye.xml


In [41]:
test_image = cv2.imread('people.jpg')
model_face = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
model_eyes = cv2.CascadeClassifier('haarcascade_eye.xml')
demo_face = model_face.detectMultiScale(test_image,1.05,2)
demo_eyes = model_eyes.detectMultiScale(test_image,1.05,5)
for (x,y,w,h) in demo_face:
  cv2.rectangle(test_image,(x,y),(x+w,y+h),(0,255,255),2)
for (x,y,w,h) in demo_eyes:
  cv2.rectangle(test_image,(x,y),(x+w,y+h),(255,0,0),2)
cv2.imshow('Facial Recognition',test_image)
cv2.waitKey(0)
cv2.destroyAllWindows()